---
title: "Final project draft"
subtitle: "MFA article coding"
---

```{r}
## Import dataset

wines<-read.csv("https://raw.githubusercontent.com/ucb-stat243/stat243-fall-2016/master/problem-sets/final-project/data/wines.csv")

Y1 <- as.matrix(wines[2:7])
Y2 <- as.matrix(wines[8:13])
Y3 <- as.matrix(wines[14:19])
Y4 <- as.matrix(wines[20:24])
Y5 <- as.matrix(wines[25:30])
Y6 <- as.matrix(wines[31:35])
Y7 <- as.matrix(wines[36:39])
Y8 <- as.matrix(wines[40:45])
Y9 <- as.matrix(wines[46:50])
Y10 <- as.matrix(wines[51:54])
```

```{r}
# Scaling
X1<- scale(Y1, center=TRUE)/sqrt(11) #54
X2<- scale(Y2, center=TRUE)/sqrt(11)
X3<- scale(Y3, center=TRUE)/sqrt(11)
X4<- scale(Y4, center=TRUE)/sqrt(11)
X5<- scale(Y5, center=TRUE)/sqrt(11)
X6<- scale(Y6, center=TRUE)/sqrt(11)
X7<- scale(Y7, center=TRUE)/sqrt(11)
X8<- scale(Y8, center=TRUE)/sqrt(11)
X9<- scale(Y9, center=TRUE)/sqrt(11)
X10<- scale(Y10, center=TRUE)/sqrt(11)
```

```{r}
# PCA of each data table
library(MASS)
svd1<-svd(X1)
U1<- svd1$u #56
V1<- svd1$v #58
D1<- svd1$d
gamma1<-diag(D1) #57
G1<- U1%*%gamma1 #59
alpha1<- D1[1]^-2 #60

svd2<-svd(X2)
U2<- svd2$u #56
V2<- svd2$v #58
D2<- svd2$d
gamma2<-diag(D2) #57
G2<- U2%*%gamma2 #59
alpha2<- D2[1]^-2 #60

svd3<-svd(X3)
U3<- svd3$u #56
V3<- svd3$v #58
D3<- svd3$d
gamma3<-diag(D3) #57
G3<- U3%*%gamma3 #59
alpha3<- D3[1]^-2 #60

svd4<-svd(X4)
U4<- svd4$u #56
V4<- svd4$v #58
D4<- svd4$d
gamma4<-diag(D4) #57
G4<- U4%*%gamma4 #59
alpha4<- D4[1]^-2 #60

svd5<-svd(X5)
U5<- svd5$u #56
V5<- svd5$v #58
D5<- svd5$d
gamma5<-diag(D5) #57
G5<- U5%*%gamma5 #59
alpha5<- D5[1]^-2 #60

svd6<-svd(X6)
U6<- svd6$u #56
V6<- svd6$v #58
D6<- svd6$d
gamma6<-diag(D6) #57
G6<- U6%*%gamma6 #59
alpha6<- D6[1]^-2 #60

svd7<-svd(X7)
U7<- svd7$u #56
V7<- svd7$v #58
D7<- svd7$d
gamma7<-diag(D7) #57
G7<- U7%*%gamma7 #59
alpha7<- D7[1]^-2 #60

svd8<-svd(X8)
U8<- svd8$u #56
V8<- svd8$v #58
D8<- svd8$d
gamma8<-diag(D8) #57
G8<- U8%*%gamma8 #59
alpha8<- D8[1]^-2 #60

svd9<-svd(X9)
U9<- svd9$u #56
V9<- svd9$v #58
D9<- svd9$d
gamma9<-diag(D9) #57
G9<- U9%*%gamma9 #59
alpha9<- D9[1]^-2 #60

svd10<-svd(X10)
U10<- svd10$u #56
V10<- svd10$v #58
D10<- svd10$d
gamma10<-diag(D10) #57
G10<- U10%*%gamma10 #59
alpha10<- D10[1]^-2 #60
```

```{r}
# Weight vector (alpha)
alpha<- as.vector(rbind(alpha1,alpha2,alpha3,alpha4,alpha5,alpha6,alpha7,alpha8,alpha9,alpha10)) #61
a<-c(rep(alpha1,6),rep(alpha2,6),rep(alpha3,6),rep(alpha4,5),rep(alpha5,6),rep(alpha6,5),rep(alpha7,4),rep(alpha8,6),rep(alpha9,5),rep(alpha10,4))
A<- diag(a) #62
```

```{r}
# Mass matrix (M)
M<- diag(rep(1/12,12)) #63
```

```{r}
# Generalized PCA of X
X<- cbind(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10)
# or 
#X<-as.matrix(wines[2:54])
#X<-scale(X)/sqrt(11) 
sqrtM<-sqrt(M)
sqrtA<-sqrt(A)
delta<-svd(sqrtM%*%X%*%sqrtA)$d    #64-2
P<-solve(sqrtM)%*%(svd(sqrtM%*%X%*%sqrtA)$u) #64-1
Q<-solve(sqrtA)%*%(svd(sqrtM%*%X%*%sqrtA)$v)
F<-P%*%diag(delta)   #65
```

```{r}
#Partial Factor Scores
# is it always Q[,1:2]??
F1<-10*alpha1*X1%*%Q[1:6,1:2] #66
F2<-10*alpha2*X2%*%Q[7:12,1:2] #66
F3<-10*alpha3*X3%*%Q[13:18,1:2] #66
F4<-10*alpha4*X4%*%Q[19:23,1:2] #66
F5<-10*alpha5*X5%*%Q[24:29,1:2] #66
F6<-10*alpha6*X6%*%Q[30:34,1:2] #66
F7<-10*alpha7*X7%*%Q[35:38,1:2] #66
F8<-10*alpha8*X8%*%Q[39:44,1:2] #66
F9<-10*alpha9*X9%*%Q[45:49,1:2] #66
F10<-10*alpha10*X10%*%Q[50:53,1:2] #66
```

```{r}
#Supplementary Table
supx<-wines[55:58]
supx<-scale(supx)/sqrt(11)  #centering and normalizing the supplementary table
xsup<-supx/max(svd(supx)$d) #69
delta<-diag(delta[1:2])
Qsup<-t(xsup)%*%M%*%P[,1:2]%*%solve(delta) #70
Fsup<-xsup%*%Qsup #71
```

```{r}
#Bootstrap

# straighten out all the factor scores
f1<-as.vector(F1)
f2<-as.vector(F2)
f3<-as.vector(F3)
f4<-as.vector(F4)
f5<-as.vector(F5)
f6<-as.vector(F6)
f7<-as.vector(F7)
f8<-as.vector(F8)
f9<-as.vector(F9)
f10<-as.vector(F10)

FF <- rbind(f1,f2,f3,f4,f5,f6,f7,f8,f9,f10)

set.seed(1)
bootstrapsample<- FF[sample(10,size=10,replace=TRUE),]
#estimated bootstrap factor score
matrix(apply(bootstrapsample,2, mean),nrow=12,ncol=2)

#bootstrapped estimate of the variance
# I think this is sample mean tho (B-1), should we multiply (B-1)/B?
matrix(apply(bootstrapsample,2, var),nrow=12,ncol=2)
```

```{r}
#HMFA: Hierarchical Multiple Factor Analysis

#normalizing and centering the first five table
table1<-X1/max(svd(X1)$d)
table2<-X2/max(svd(X2)$d)
table3<-X3/max(svd(X3)$d)
table4<-X4/max(svd(X4)$d)
table5<-X5/max(svd(X5)$d) 

table_first5<-cbind(table1,table2,table3,table4,table5) #get the "men-table"
number1<-max(svd(table_first5)$d)#the first singular value of this ‘men-table’ 

#then, assume we get the first singular value of the last five table is number2=2.169
number2<-2.169
number<-c(rep(number1^(-2),5),rep(number2^(-2),5))
alpha_HMFA<-alpha*number #77

a_HMFA<-c(rep(alpha_HMFA[1],6),rep(alpha_HMFA[2],6),rep(alpha_HMFA[3],6),rep(alpha_HMFA[4],5),rep(alpha_HMFA[5],6),rep(alpha_HMFA[6],5),rep(alpha_HMFA[7],4),rep(alpha_HMFA[8],6),rep(alpha_HMFA[9],5),rep(alpha_HMFA[10],4))
A_HMFA<-diag(a_HMFA)
Y_HMFA<-sqrt(M)%*%X%*%sqrt(A_HMFA)
delta_HMFA<-svd(Y_HMFA)$d    #get the sigular value  
P_HMFA<-solve(sqrtM)%*%(svd(Y_HMFA)$u)
F_HMFA<-P_HMFA%*%diag(delta_HMFA)   #78
```
